### ISSUE TITLE
导入错误

### ISSUE THREAD

**Issue by jingyuexing** [1eez/103976#1]
INSERT INTO EnWords VALUES ('disembargo','v.�������');
INSERT INTO EnWords VALUES ('disembark','v.(ʹ)��,(ʹ)��½');
INSERT INTO EnWords VALUES ('disembarkation','n.��,��½');
INSERT INTO EnWords VALUES ('disembarrass','vt.ʹ����(�����)���������ա������');
INSERT INTO EnWords VALUES ('disembarrassment','n.ʹ��������,ʹ����');
INSERT INTO EnWords VALUES ('disembodied','adj.��ʵ�ʵ�,��ʵ���');
INSERT INTO EnWords VALUES ('disembodiment','n.����,����');
INSERT INTO EnWords VALUES ('disembody','vt.ʹ��������(������)');
INSERT INTO EnWords VALUES ('disembogue','v.ע��,����');
INSERT INTO EnWords VALUES ('disemboguement','n.��ע');
INSERT INTO EnWords VALUES ('disembosom','vt.��¶,й¶');
INSERT INTO EnWords VALUES ('disembowel','vt.��ȥ(��ȡ��)...�ĳ���(�������)');
INSERT INTO EnWords VALUES ('disembroil','vt.�Ž����');
INSERT INTO EnWords VALUES ('disemplane','v.�·ɻ�');
INSERT INTO EnWords VALUES ('disemploy','v.����,���');
INSERT INTO EnWords VALUES ('disemployment','n.����,���');
INSERT INTO EnWords VALUES ('disenable','v.ʹ����,ʹɥʧ�ʸ�');
INSERT INTO EnWords VALUES ('disenablement','n.ʹ����,ɥʧ�ʸ�');
INSERT INTO EnWords VALUES ('disenchant','vt.ʹ����');
INSERT INTO EnWords VALUES ('disenchanted','�������Ե�');
INSERT INTO EnWords VALUES ('disenchanting','ʹ�������Ե�');
INSERT INTO EnWords VALUES ('disenchantment','n.����,����');
INSERT INTO EnWords VALUES ('disencumber','vt.���ѷ���,���ܷ���');
INSERT INTO EnWords VALUES ('disendow','vt.û�ջ���');
INSERT INTO EnWords VALUES ('disendowment','n.�������');
INSERT INTO EnWords VALUES ('disenfranchise','v.(=disfranchise)����...����Ȩ');
INSERT INTO EnWords VALUES ('disengage','v.����');
INSERT INTO EnWords VALUES ('disengaged','adj.���ɵ�,��ɢ��,���е�');
INSERT INTO EnWords VALUES ('disengagement','n.����');
INSERT INTO EnWords VALUES ('disennoble','v.ʹ�ͼ�,����Ʒ��');
INSERT INTO EnWords VALUES ('disenroll','v.����,����');
INSERT INTO EnWords VALUES ('disentail','v.��ȥ�̳�Ȩ������');
INSERT INTO EnWords VALUES ('disentangle','vi.����,�⿪����,�ɿ�,���(����)vt.�⿪,�ɿ�');
INSERT INTO EnWords VALUES ('disentanglement','n.�⿪����');
INSERT INTO EnWords VALUES ('disenthral','vt.���');
INSERT INTO EnWords VALUES ('disenthrall','v.�ͷ�');
INSERT INTO EnWords VALUES ('disenthralment','n.���');
INSERT INTO EnWords VALUES ('disenthrone','v.�ϳ���λ(��λ)');
INSERT INTO EnWords VALUES ('disentitle','v.����...��Ȩ��,����...�ĳƺ�');
INSERT INTO EnWords VALUES ('disentomb','v.����');
INSERT INTO EnWords VALUES ('disentrance','v.ʹ������о���

**Comment by 1eez** [comment]
汉字编码问题，导入时，请选择UTF-8格式才能正常显示。
